### ISSUE TITLE
Streaming takes complete control of audio

### ISSUE THREAD

**Issue by dimitrisTim** [dtcooper/raspotify#111]
While I am using the library, it takes complete control of the audio device, not letting other sound sources (like a youtube video) make a playback at the same time with the music coming from spotify.

Is this related to my audio configuration on Rpi or is it an issue of the library?

**Comment by dtcooper** [comment]
This is an alsa thing unfortunately. Have you tried using it with pulseaudio? YMMV however.

**Comment by Yaxit** [comment]
I looked into and I found an appropriate solution. The basic idea is to configure Alsa to mix all inputs into a single output. This can be done editing Alsa global config files.
Edit the global Alsa config ( `sudo nano /etc/asound.conf` ) as follows:
```
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}

pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "mixery"
  }
}
pcm.mixery {
  type dmix
  ipc_key 1024
  ipc_perm 0666
  ipc_key_add_uid false
  slave {
    pcm "hw:1,0"
  }
}
```
In a nutshell, what this configuration does is set the default pcm audio device to pass any audio stream to the pcm.mixery device, which mixes all the incoming streams and outputs in the hw:1,0.
It also sets microfone on hw:1,0 but this is not rilevant.

You will then run raspotify with the --device option editing its start parameters ( `sudo nano /lib/systemd/system/raspotify.service` ) and adding `--device speaker` at ExecStart line.

The configuration MUST be in the global config file `/etc/asound.conf` and not in your personal config `.asoundrc` because Raspotify actually belongs to a different user, having his own Alsa config file in his own home directory.
PS: you will have to edit device and cards numbers depending on your configuration.

**Comment by JasonLG1979** [comment]
Raspotify is primarily intended to be used in a headless enviroment (Raspberry Pi OS lite) For desktop versions of Raspberry Pi OS (and/or systems with PulseAudio installed) [spotifyd](https://spotifyd.github.io/spotifyd/installation/Raspberry-Pi.html) offers similar functionality, much better PulseAudio compatibility and is a better choice.
