### ISSUE TITLE
Stops playing after a few songs, FIX

### ISSUE THREAD

**Issue by oscar-chavez** [dtcooper/raspotify#124]
I realized that after a whle the songs would stop playing, so I began to play with some settings and I found out that the music continues after muting and unmuting the volume. So I created a simple script to do this https://gist.github.com/oscar-chavez/b285b9f98d852aba1dee02b76967bdbc
once you have that .sh file, run _crontab -e _ and type */3 * * * * Desktop/raspotifyfix.sh

Hope this helps, it worked for me.

**Comment by thexmanxyz** [comment]
@oscar-chavez The fix does not work and it's also not really a nice solution. But the issue is real. I also have the problem. If you change the volume the sound is back. The songs seem to play but there is no sound output produced. I also found out that restarting the service will solve the issue too.

But actually this bug breaks the general functionality and makes it nearly unusuable. Someone a working fix?
