### ISSUE TITLE
Using ALSA DAPM to operate an RELAY to toggle amplifier ON/OFF

### ISSUE THREAD

**Issue by matzejo** [dtcooper/raspotify#290]
Is it possible to add this function to the code?
There is written that you use the ASLA DAPM. 
Please have a look here for the EVENT HANDLER https://www.alsa-project.org/wiki/DAPM

I tried to toggle my amp on/off to safe power but unfortunately i´m not very experienced in coding.
https://www.instructables.com/id/5V-Relay-Raspberry-Pi/g

So it would be great if you could do it :) or maybe someone who knows howto.

thx for this good work.

**Comment by JasonLG1979** [comment]
That's way beyond the scope of raspotify, but if I'm guessing right you want turn something on when music starts playing and turn it off when the music stops. If you don't mind the that the solution is librespot specific it would probably be easier to use the ```--onevent``` option and fire a script off that controls the relay. Another solution if the device you want to control has a IR receiver it to just use a IR transmitter instead of a relay. So for example you want to turn on your AVR automatically when librespot starts playing, and/or you want it to automatically shut off when the music stops.
