### ISSUE TITLE
Make ubuntu 64 bit version for use with x86

### ISSUE THREAD

**Issue by thisisawesome1994** [dtcooper/raspotify#410]
Hi,

Can you please make a version available for 64 bit x86 computers, running ubuntu server 20.04 for example.

Maybe make version that supports hifi at spotify hifi launch?

Awaiting your response,
Thisisawesome1994

**Comment by JasonLG1979** [comment]
> Can you please make a version available for 64 bit x86 computers, running ubuntu server 20.04 for example.

Raspotify is basically just [librespot](https://github.com/librespot-org/librespot) compiled for Raspberry Pi's with a systemd unit and some tweaks to make librespot a systemd service.

An x86_64 version is out of scope of Raspotify, but you can easily [compile an X86_64 version yourself](https://github.com/librespot-org/librespot/blob/master/COMPILING.md) and use the [Raspotify systemd unit file](https://github.com/dtcooper/raspotify/blob/master/raspotify/lib/systemd/system/raspotify.service) as inspiration/a starting point and end up with what you're asking for.

> Maybe make version that supports hifi at spotify hifi launch?

Again since Raspotify is a binary of librespot compiled for Raspberry Pi's it's not up to this project to add features. That would be on librespot. The latest API is being reverse engineered currently (the playback API's are not publicly documented by Spotify. It's a bit of a Guerrilla effort) When HiFi launches in the dev's areas I'm sure they'll want to add the feature.
