### ISSUE TITLE
Doesnt play whole playlists

### ISSUE THREAD

**Issue by Pukesmiley** [dtcooper/raspotify#419]
My standard playlist is 2500+ songs big, but when i play it on the Pi it only shuffles the first 80+- and beginns with the first song in the playlist.
Im using the 3B+

**Comment by JasonLG1979** [comment]
The new release is live. Please update and see if that solves your issue.

**Comment by maxmidnite** [comment]
Now I can't connect at all anymore. I don't have time to check what's wrong right now. I'll get to it later, worst case I'll reset the system and let you know.

**Comment by JasonLG1979** [comment]
This particular problem is an upstream issue. If after updating to the latest version of Raspotify the issue persists please file a bug with `librespot`.

Otherwise if the reason you can't connect is something different please feel free to open a different issue here if it's related to packaging or configuration or `librespot` if it's related to how the `librespot` binary behaves.
