### ISSUE TITLE
Change FIFO Output

### ISSUE THREAD

**Issue by BS-zombie** [dtcooper/raspotify#462]
Hello, and sorry for the noob question. I am trying to get [this](https://github.com/barrymcandrews/aurora-server) to work, but I have very little knowledge of anything to do with audio on linux. I can't find anything about this in any documentation, so could someone help me if its not too much bother?

Thanks, and great work on this!

**Comment by JasonLG1979** [comment]
1. This is not really the place to ask for help with another project. Raspotify is just listed as an example. You should ask for help their.

2. That repo hasn't had a commit in 3 years. It may not be maintained any longer?

3. The docs regarding Raspotify are outdated.

4. Raspotify has no access to `/tmp` for security reasons (and also because Raspotify doesn't use `/tmp` for anything at all) so the `fifo` can't be in `/tmp` so the [default location used by aurora-server](https://github.com/barrymcandrews/aurora-server/blob/develop/config/aurora.conf#L71) will not work.

5. [Number 4 is documented in the wiki](https://github.com/dtcooper/raspotify/wiki/Troubleshooting).

I'm closing this as invalid. This is not a Raspotify issue or even configuration issue.
