### ISSUE TITLE
Syntax error in installation script

### ISSUE THREAD

**Issue by SebastianZimmer** [dtcooper/raspotify#519]
### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Latest Version

- [X] I'm running the latest version of Raspotify

### Due Diligence

- [X] I have done my due diligence

### What happened?

The installation of Raspotify via `install.sh` fails due to a syntax error. This was still working a few days ago, so I suspect a regression.

### Relevant log output

```shell
$ curl -sL https://dtcooper.github.io/raspotify/install.sh | sh
sh: 60: Syntax error: "(" unexpected (expecting "then")
```

**Comment by SebastianZimmer** [comment]
duplicate of https://github.com/dtcooper/raspotify/issues/517

**Comment by bobrathbone** [comment]
Run the following instructions (Use bash instead of sh)

sudo apt-get install apt-transport-https
curl -sL https://dtcooper.github.io/raspotify/install.sh | bash

Also note that support for Raspotify on Buster has been dropped. You need to run it on Bullseye. 

Already raised in issue 517 See https://github.com/dtcooper/raspotify/issues/517

**Comment by SebastianZimmer** [comment]
Thanks! It works now. Btw, I did run this on Bullseye in the first place and had the syntax error there.

**Comment by bobrathbone** [comment]
Glad it is working. I have left a comment in https://github.com/dtcooper/raspotify/issues/517 that the page at https://github.com/dtcooper/raspotify/ ought to be updated with the corrected installation instructions.
