### ISSUE TITLE
please stop doing no sense commits and updates

### ISSUE THREAD

**Issue by GiaSen** [dtcooper/raspotify#600]
### Due Diligence

- [X] I have done my due diligence

### What can we help you with?

you are sending multiple useless updates, just don't do useless commits

**Comment by JasonLG1979** [comment]
1. I will do what I please.

2. They are not useless. Every Raspotify update may also represent updates in the librespot fork, which are not a part of this repo. What may look like stupid updates are actually needed otherwise if a change happens in the librespot repo I can not do a new release unless there is a change in the Raspotify repo.

**Comment by GiaSen** [comment]
okay, sorry for the issues, still thanks for the great tool, and good luck :)
